import type {NextPage} from 'next'
import Head from 'next/head'
import {Header} from "../components/layout/Header";
import dynamic from "next/dynamic";

const Editor = dynamic(() => import('../components/Editor/Editor'), {
    ssr: false
})

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header />
            <Editor />
        </>
    )
}

export default Home
